name: laker_2
description: "Versi bloc"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  bloc: ^9.2.0
  device_preview: ^1.3.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  flutter_svg: ^2.2.3
  fpdart: ^1.2.0
  get_it: ^9.2.1
  go_router: ^17.1.0
  percent_indicator: ^4.2.5
  supabase: ^2.10.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  build_runner: ^2.11.1
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.2.0

flutter:
  assets: 
    - assets/images/
  fonts: 
    - family: Mogra
      fonts: 
        - asset: assets/fonts/Mogra-Regular.ttf
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  uses-material-design: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 100 # Optional (default: 80)
  assets:
    enabled: true
    outputs:
      class_name: Aset # Optional (default: Assets)
      package_parameter_enabled: false

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png" # Siapkan file icon.png kamu di sini