name: laker_2
description: "Versi bloc"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^6.0.3
  dartz: ^0.10.1
  device_preview: ^1.3.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  get_it: ^8.2.0
  go_router: ^16.3.0
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets: 
    - assets/images/
  fonts: 
    - family: Mogra
      fonts: 
        - asset: assets/fonts/Mogra-Regular.ttf
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  uses-material-design: true
